# Generated by Django 5.2.9 on 2026-01-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line1',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('business', 'Business'), ('worker', 'Worker')], default='worker', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
