# Generated by Django 5.2.9 on 2026-01-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location_lng',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
