# Generated by Django 5.2.9 on 2026-01-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('approved', 'Approved'), ('paid', 'Paid')], default='open', max_length=20),
        ),
    ]
