from rest_framework import serializers
from django.contrib.auth.models import User
from .models import Task, UserProfile


# `fields` controls what the API exposes and accepts:
# - For GET requests → only these fields are shown in the response
# - For POST/PUT requests → only these fields are accepted from the client
# Fields not listed here are ignored, even if they exist in the model.

class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ['id', 'username', 'email']

class TaskSerializer(serializers.ModelSerializer):
    # Nested serializer to DISPLAY business user details in GET responses
    # read_only=True means:
    # - Client CANNOT send or change business data
    # - Backend sets business automatically (request.user)
    business = UserSerializer(read_only=True)
    proof_image = serializers.ImageField(required=False, allow_null=True)
    
    class Meta:
        model = Task
        fields = '__all__'
        
        # These fields are CONTROLLED BY BACKEND only
        # - id → auto-generated by DB
        # - created_at → auto-set on creation
        # - status → managed by backend logic, not client input
        read_only_fields = ['id', 'created_at', 'status']


class UserProfileSerializer(serializers.ModelSerializer):
    """
    Used ONLY for REGISTRATION (POST /api/register/)
    Purpose: Creates NEW UserProfile during signup
    Fields: Only writable fields needed for creation (no user - auto-created)
    """
    class Meta:
        model = UserProfile
        fields = ['role', 'phone', 'address']


class ProfileSerializer(serializers.ModelSerializer):
    """
    Used for VIEW/UPDATE profile (GET/PUT /api/profile/)
    Purpose: Shows COMPLETE profile info + username for logged-in user
    Fields: Includes user details (read-only) for full profile display
    Why separate: Registration creates, Profile displays/updates
    """
    user = UserSerializer(read_only=True)
    
    class Meta:
        model = UserProfile
        fields = ['user', 'role', 'phone', 'address']
        read_only_fields = ['user']


# RegisterSerializer accepts user + profile data, securely creates a User, hashes the password, 
# creates a related UserProfile, and links them together in one request.
class RegisterSerializer(serializers.ModelSerializer):
    password = serializers.CharField(write_only=True)
    profile = UserProfileSerializer()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'profile']
    
    def create(self, validated_data):
        profile_data = validated_data.pop('profile')
        password = validated_data.pop('password')
        user = User.objects.create_user(**validated_data)
        user.set_password(password)
        user.save()
        UserProfile.objects.create(user=user, **profile_data)
        return user


